[config]
schemaVersion = "0.0.1"

[package]
namespace = "Ixrec"
name = "ArchipelagoRandomizer"
versionNumber = "0.3.1"
description = "A Nine Sols mod for the Archipelago multi-game randomizer system"
websiteUrl = "https://github.com/Ixrec/NineSolsArchipelagoRandomizer"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "0.0.2"
"Ixrec-TeleportFromAnywhere" = "0.2.0"
"ninesolsmodding-BepinExConfigurationManager" = "18.3.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
